version: '2.1'
services:
  dynamodb:
    image: amazon/dynamodb-local:1.18.0
    command: -jar DynamoDBLocal.jar -sharedDb -inMemory -port 8001
    ports:
      - '8001:8001'
    working_dir: /home/dynamodblocal